### ISSUE TITLE
healenium-appium-1.1 jar issue

### ISSUE THREAD

**Issue by Sugi0109** [healenium/example_appium_mvn#4]
I have imported example-appium-mvn maven project, when I update the pom.xml all the dependencies got downloaded but healenium-appium-1.1 jar seems to be broken because of that it shows error in the import statement (com.epam.healenium.appium.DriverWrapper)in my test case. Please help me in resolving this.

**Comment by AnatoliZaitsau** [comment]
The project healenium-appium has been updated to version 1.2
